name: JavaScript Lint Check (Clients Folder)

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint on Clients Folder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint and Capture Output
        id: eslint_check
        run: |
          ESLINT_OUTPUT=$(npx eslint clients/ --ext .js,.jsx,.ts,.tsx --format=json)
          echo "$ESLINT_OUTPUT" > eslint_output.json
          echo "ESLINT_FOUND_ERRORS=$(echo "$ESLINT_OUTPUT" | jq 'map(select(.errorCount > 0 or .warningCount > 0)) | length')" >> $GITHUB_ENV

      - name: Debug ESLint Results
        run: cat eslint_output.json

      - name: Send Slack Notification on ESLint Errors or Warnings
        if: env.ESLINT_FOUND_ERRORS != '0'
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{
            "type": "event",
            "event": {
              "text": "🚨 *ESLint Found Issues in Clients Folder!* 🚨",
              "fields": {
                "Repository": "${{ github.repository }}",
                "Branch": "${{ github.ref }}",
                "Commit": "${{ github.sha }}",
                "Actor": "${{ github.actor }}",
                "Details": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>"
              }
            }
          }' ${{ secrets.SLACK_AUTOMATION_WEBHOOK_URL }}
