name: ESLint Check and Notify Slack

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: |
          npx eslint . --format json --output-file eslint-report.json || true

      - name: Check ESLint Results
        id: check_eslint
        run: |
          ERROR_COUNT=$(jq '[.[] | .errorCount] | add' eslint-report.json)
          if [ "$ERROR_COUNT" -gt 0 ]; then
            echo "has_errors=true" >> $GITHUB_ENV
          else
            echo "has_errors=false" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification
        if: always() # Always run this step
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "$has_errors" = "true" ]; then
            STATUS=":x: ESLint found errors in the latest push."
          else
            STATUS=":white_check_mark: ESLint passed with no errors."
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${STATUS}\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}>\"
          }" $SLACK_WEBHOOK_URL
